export { default as Footer } from './Footer.jsx'
export { default as Header } from './Header.jsx'
export { default as SearchBar } from './SearchBar.jsx'
export { default as MovieFilter } from './MovieFilter.jsx'
export { default as Loader } from './Loader.jsx'
